# fly.toml app configuration file for MsgCore
#
# To deploy to Fly.io:
# 1. Run: fly launch
# 2. Fly will detect this config and prompt you to choose your app name and region
# 3. After launch, set your secrets (see README.md for the list)
# 4. Deploy with: fly deploy
#
# See https://fly.io/docs/reference/configuration/ for more information.
#

# app = 'your-app-name'        # Uncomment and set your app name, or let 'fly launch' do it
# primary_region = 'gig'        # Uncomment and set your region, or let 'fly launch' do it

[build]

[deploy]
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
